services:
  n8n:
    image: n8n-nodes-line-messaging
    build: .
    command: 'start --tunnel'
    restart: always
    ports:
      - '5678:5678'
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_ENV=development
      - N8N_RUNNERS_ENABLED=true
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: nodes/
        - action: rebuild
          path: credentials/
    volumes:
      - ./.n8n:/home/node/.n8n
