name: Bug Report
description: Report a bug or issue with n8n-nodes-line-messaging
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: When I try to... the node fails with...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Create a workflow with...
        2. Configure the node with...
        3. Execute the workflow...
        4. Observe the error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The node should...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, the node...
    validations:
      required: true

  - type: dropdown
    id: node-type
    attributes:
      label: Node Type
      description: Which node is experiencing the issue?
      options:
        - LineMessaging (main messaging node)
        - LineMessagingData (content retrieval)
        - LineMessagingTrigger (webhook)
    validations:
      required: true

  - type: dropdown
    id: operation
    attributes:
      label: Operation
      description: Which operation were you using?
      options:
        - Reply
        - Send
        - Multicast
        - Get Profile
        - Get Content
        - Webhook
        - Other
    validations:
      required: true

  - type: input
    id: n8n-version
    attributes:
      label: n8n Version
      description: What version of n8n are you using?
      placeholder: e.g., 1.15.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node Package Version
      description: What version of @aotoki/n8n-nodes-line-messaging are you using?
      placeholder: e.g., 0.8.1
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where is n8n running?
      options:
        - Self-hosted (Docker)
        - Self-hosted (npm)
        - n8n Cloud
        - Other
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Please copy and paste any error messages or logs (they will be automatically formatted)
      render: shell
    validations:
      required: false

  - type: textarea
    id: workflow-json
    attributes:
      label: Workflow JSON (Optional)
      description: If possible, export and paste your workflow JSON (remove sensitive data first)
      render: json
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem, including screenshots
      placeholder: |
        Screenshots:
        Related LINE API behavior:
        Workarounds attempted:
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have removed any sensitive information from my report (tokens, secrets, personal data)
          required: true
