on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
        id: release
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        if: ${{ steps.release.outputs.release_created }}
      - name: Install pnpm
        uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          scope: '@aotoki'
      - run: pnpm install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm build
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm publish --access public --no-git-checks
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_MODE: 'true' # Avoid n8n-node prerelease breaking
